env:
  browser: true
  es2021: true
  node: true
  jest: true
extends: eslint:recommended
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: latest
  sourceType: module
rules:
  no-underscore-dangle:
  - 2
  - allow:
    - __filename
    - __dirname
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
  trailing-comma:
    - false